// Generated by npm run build:abilities. Do not edit by hand.

// src/tags/Tag.ts
var TAG_PATTERN = /^[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)*$/;
function defineTag(value) {
  if (!TAG_PATTERN.test(value)) {
    throw new TypeError(
      `\u65E0\u6548\u6807\u7B7E\u300C${value}\u300D\uFF1A\u5FC5\u987B\u4F7F\u7528\u7531\u5B57\u6BCD\u3001\u6570\u5B57\u6216\u4E0B\u5212\u7EBF\u7EC4\u6210\u7684\u70B9\u5206\u5C42\u7EA7\uFF0C\u4F8B\u5982 Input.Player.Move`
    );
  }
  return value;
}
function isValidTag(value) {
  return typeof value === "string" && TAG_PATTERN.test(value);
}
function tagMatches(tag, query) {
  const candidate = defineTag(tag);
  const expected = defineTag(query);
  return candidate === expected || candidate.startsWith(`${expected}.`);
}

// src/tags/TagContainer.ts
var TagContainer = class _TagContainer {
  tags = /* @__PURE__ */ new Set();
  constructor(initialTags) {
    if (initialTags !== void 0) this.addAll(initialTags);
  }
  static from(...tags) {
    return new _TagContainer(tags);
  }
  get size() {
    return this.tags.size;
  }
  /** 添加显式标签。重复添加不会改变容器。 */
  add(tag) {
    this.tags.add(defineTag(tag));
    return this;
  }
  addAll(tags) {
    for (const tag of this.iterateCollection(tags)) this.add(tag);
    return this;
  }
  /** 只删除显式保存的同名标签。 */
  delete(tag) {
    return this.tags.delete(defineTag(tag));
  }
  clear() {
    this.tags.clear();
  }
  /** 是否显式保存了完全相同的标签。 */
  hasExact(tag) {
    return this.tags.has(defineTag(tag));
  }
  /**
   * 是否包含能够匹配查询的标签。
   * 容器中的子标签可以匹配其父级查询，父标签不能匹配更具体的子级查询。
   */
  hasTag(tag) {
    for (const ownedTag of this.tags) {
      if (tagMatches(ownedTag, tag)) return true;
    }
    return false;
  }
  hasAny(tags) {
    for (const tag of this.iterateCollection(tags)) {
      if (this.hasTag(tag)) return true;
    }
    return false;
  }
  hasAll(tags) {
    for (const tag of this.iterateCollection(tags)) {
      if (!this.hasTag(tag)) return false;
    }
    return true;
  }
  hasAnyExact(tags) {
    for (const tag of this.iterateCollection(tags)) {
      if (this.hasExact(tag)) return true;
    }
    return false;
  }
  hasAllExact(tags) {
    for (const tag of this.iterateCollection(tags)) {
      if (!this.hasExact(tag)) return false;
    }
    return true;
  }
  clone() {
    return new _TagContainer(this);
  }
  /** 返回显式标签的插入顺序快照。 */
  toArray() {
    return [...this.tags];
  }
  [Symbol.iterator]() {
    return this.tags.values();
  }
  *iterateCollection(collection) {
    if (typeof collection === "string") {
      yield collection;
      return;
    }
    yield* collection;
  }
};

// src/abilities/AttributeSet.ts
var ATTRIBUTE_ID_PATTERN = /^[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)*$/;
function assertFinite(value, label) {
  if (!Number.isFinite(value)) throw new TypeError(`${label} \u5FC5\u987B\u662F\u6709\u9650\u6570\u5B57`);
}
function clamp(value, minimum, maximum) {
  return Math.min(Math.max(value, minimum), maximum);
}
function applyOperation(value, operation, magnitude) {
  switch (operation) {
    case "add":
      return value + magnitude;
    case "multiply":
      return value * magnitude;
    case "override":
      return magnitude;
  }
}
var JavascriptAttributeBackend = class {
  calculate(inputs) {
    const output = /* @__PURE__ */ new Map();
    for (const input of inputs) {
      let value = input.baseValue;
      const modifiers = [...input.modifiers].sort((left, right) => left.priority - right.priority || left.order - right.order);
      for (const modifier of modifiers) {
        value = applyOperation(value, modifier.operation, modifier.magnitude);
      }
      output.set(input.attributeId, clamp(value, input.minimum, input.maximum));
    }
    return output;
  }
};
var AttributeSet = class {
  states = /* @__PURE__ */ new Map();
  backend;
  onChanged;
  constructor(definitions = [], options = {}) {
    this.backend = options.backend ?? new JavascriptAttributeBackend();
    this.onChanged = options.onChanged;
    for (const definition of definitions) this.define(definition);
  }
  define(definition) {
    if (!ATTRIBUTE_ID_PATTERN.test(definition.id)) {
      throw new TypeError(`\u5C5E\u6027 id \u683C\u5F0F\u65E0\u6548\uFF1A${definition.id}`);
    }
    if (this.states.has(definition.id)) throw new Error(`\u5C5E\u6027\u91CD\u590D\u5B9A\u4E49\uFF1A${definition.id}`);
    assertFinite(definition.initialValue, `\u5C5E\u6027 ${definition.id} \u7684 initialValue`);
    const minimum = definition.minimum ?? Number.NEGATIVE_INFINITY;
    const maximum = definition.maximum ?? Number.POSITIVE_INFINITY;
    if (minimum > maximum) throw new RangeError(`\u5C5E\u6027 ${definition.id} \u7684 minimum \u4E0D\u80FD\u5927\u4E8E maximum`);
    const initialValue = clamp(definition.initialValue, minimum, maximum);
    this.states.set(definition.id, {
      definition: { ...definition, initialValue },
      baseValue: initialValue,
      currentValue: initialValue
    });
  }
  has(attributeId) {
    return this.states.has(attributeId);
  }
  getBaseValue(attributeId) {
    return this.requireState(attributeId).baseValue;
  }
  getCurrentValue(attributeId) {
    return this.requireState(attributeId).currentValue;
  }
  setBaseValue(attributeId, value) {
    assertFinite(value, `\u5C5E\u6027 ${attributeId} \u7684 BaseValue`);
    const state = this.requireState(attributeId);
    const minimum = state.definition.minimum ?? Number.NEGATIVE_INFINITY;
    const maximum = state.definition.maximum ?? Number.POSITIVE_INFINITY;
    state.baseValue = clamp(value, minimum, maximum);
  }
  modifyBaseValue(attributeId, operation, magnitude) {
    assertFinite(magnitude, `\u5C5E\u6027 ${attributeId} \u7684 Modifier magnitude`);
    const state = this.requireState(attributeId);
    this.setBaseValue(attributeId, applyOperation(state.baseValue, operation, magnitude));
  }
  recalculate(modifiers) {
    const grouped = /* @__PURE__ */ new Map();
    for (const modifier of modifiers) {
      this.requireState(modifier.attributeId);
      const bucket = grouped.get(modifier.attributeId) ?? [];
      bucket.push(modifier);
      grouped.set(modifier.attributeId, bucket);
    }
    const inputs = [];
    for (const [attributeId, state] of this.states) {
      inputs.push({
        attributeId,
        baseValue: state.baseValue,
        minimum: state.definition.minimum ?? Number.NEGATIVE_INFINITY,
        maximum: state.definition.maximum ?? Number.POSITIVE_INFINITY,
        modifiers: grouped.get(attributeId) ?? []
      });
    }
    const values = this.backend.calculate(inputs);
    for (const [attributeId, state] of this.states) {
      const calculatedValue = values.get(attributeId);
      if (calculatedValue === void 0) throw new Error(`\u5C5E\u6027\u8BA1\u7B97\u540E\u7AEF\u9057\u6F0F\u7ED3\u679C\uFF1A${attributeId}`);
      assertFinite(calculatedValue, `\u5C5E\u6027 ${attributeId} \u7684\u8BA1\u7B97\u7ED3\u679C`);
      const nextValue = clamp(
        calculatedValue,
        state.definition.minimum ?? Number.NEGATIVE_INFINITY,
        state.definition.maximum ?? Number.POSITIVE_INFINITY
      );
      if (Object.is(nextValue, state.currentValue)) continue;
      const previousValue = state.currentValue;
      state.currentValue = nextValue;
      this.onChanged?.(attributeId, previousValue, nextValue);
    }
  }
  createSnapshot() {
    return [...this.states].map(([id, state]) => ({
      id,
      baseValue: state.baseValue,
      currentValue: state.currentValue
    }));
  }
  requireState(attributeId) {
    const state = this.states.get(attributeId);
    if (!state) throw new Error(`\u672A\u77E5\u5C5E\u6027\uFF1A${attributeId}`);
    return state;
  }
};

// src/abilities/AbilitySystem.ts
var DEFINITION_ID_PATTERN = /^[A-Za-z0-9_]+(?:[.:-][A-Za-z0-9_]+)*$/;
var EMPTY_PARAMETERS = Object.freeze({});
var TIME_EPSILON = 1e-9;
function assertDefinitionId(value, label) {
  if (!DEFINITION_ID_PATTERN.test(value)) throw new TypeError(`${label} id \u683C\u5F0F\u65E0\u6548\uFF1A${value}`);
}
function assertPositiveFinite(value, label) {
  if (!Number.isFinite(value) || value <= 0) throw new RangeError(`${label} \u5FC5\u987B\u662F\u6B63\u6709\u9650\u6570\u5B57`);
}
function freezeParameters(parameters) {
  return parameters ? Object.freeze({ ...parameters }) : EMPTY_PARAMETERS;
}
var AbilitySystem = class {
  ownerId;
  attributes;
  looseTags = new TagContainer();
  grantedTagCounts = /* @__PURE__ */ new Map();
  abilities = /* @__PURE__ */ new Map();
  activeAbilities = /* @__PURE__ */ new Map();
  activeEffects = /* @__PURE__ */ new Map();
  cooldowns = /* @__PURE__ */ new Map();
  listeners = /* @__PURE__ */ new Set();
  elapsedSeconds = 0;
  nextAbilityHandle = 1;
  nextEffectHandle = 1;
  nextEffectOrder = 1;
  constructor(options) {
    if (!options.ownerId) throw new TypeError("AbilitySystem ownerId \u4E0D\u80FD\u4E3A\u7A7A");
    this.ownerId = options.ownerId;
    this.attributes = new AttributeSet(options.attributes, {
      backend: options.attributeBackend,
      onChanged: (attributeId, previousValue, currentValue) => {
        this.emit({ type: "attribute-changed", attributeId, previousValue, currentValue });
      }
    });
  }
  subscribe(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  defineAttribute(definition) {
    this.attributes.define(definition);
    this.recalculateAttributes();
  }
  addLooseTag(tag) {
    this.looseTags.add(tag);
  }
  removeLooseTag(tag) {
    return this.looseTags.delete(tag);
  }
  hasTag(query) {
    if (this.looseTags.hasTag(query)) return true;
    for (const [tag, count] of this.grantedTagCounts) {
      if (count > 0 && tagMatches(tag, query)) return true;
    }
    return false;
  }
  hasAllTags(tags) {
    return tags.every((tag) => this.hasTag(tag));
  }
  hasAnyTags(tags) {
    return tags.some((tag) => this.hasTag(tag));
  }
  grantAbility(definition, sourceId) {
    this.validateAbilityDefinition(definition);
    const handle = `ability:${this.nextAbilityHandle++}`;
    this.abilities.set(handle, {
      handle,
      definition,
      sourceId
    });
    return handle;
  }
  revokeAbility(handle) {
    const granted = this.abilities.get(handle);
    if (!granted) return false;
    this.endAbility(handle, true);
    this.abilities.delete(handle);
    return true;
  }
  findAbilityHandles(abilityId) {
    return [...this.abilities.values()].filter((granted) => granted.definition.id === abilityId).map((granted) => granted.handle);
  }
  activateAbility(handle, options = {}) {
    const granted = this.abilities.get(handle);
    if (!granted) return { ok: false, reason: "unknown-ability" };
    if (this.activeAbilities.has(handle)) return { ok: false, reason: "already-active" };
    const definition = granted.definition;
    if (!this.matchesRequirements(definition.activationRequirements)) {
      return { ok: false, reason: "tag-requirements" };
    }
    if (this.isBlockedByActiveAbility(definition)) {
      return { ok: false, reason: "blocked-by-ability" };
    }
    if (this.isConcurrencyBlocked(definition)) {
      return { ok: false, reason: "concurrency-blocked" };
    }
    const cooldownGroup = definition.cooldown?.group ?? definition.id;
    if ((this.cooldowns.get(cooldownGroup) ?? 0) > TIME_EPSILON) {
      return { ok: false, reason: "cooldown" };
    }
    for (const cost of definition.costs ?? []) {
      if (this.attributes.getCurrentValue(cost.attributeId) + TIME_EPSILON < cost.amount) {
        return { ok: false, reason: "insufficient-attribute" };
      }
    }
    for (const application of definition.effects ?? []) {
      const target = application.target === "owner" ? this : options.target;
      if (!target) return { ok: false, reason: "missing-target" };
      const additionalTags = target === this ? definition.ownedTags : void 0;
      target.validateEffectDefinition(application.effect);
      if (!target.matchesRequirements(application.effect.requirements, additionalTags)) {
        return { ok: false, reason: "effect-rejected" };
      }
    }
    for (const cost of definition.costs ?? []) {
      this.attributes.modifyBaseValue(cost.attributeId, "add", -cost.amount);
    }
    if (definition.costs?.length) this.recalculateAttributes();
    if (definition.cooldown) this.cooldowns.set(cooldownGroup, definition.cooldown.seconds);
    this.cancelAbilitiesFor(definition);
    this.cancelReplaceableAbilitiesFor(definition);
    const active = {
      granted,
      target: options.target,
      payload: options.payload
    };
    this.activeAbilities.set(handle, active);
    this.addGrantedTags(definition.ownedTags);
    this.emit({ type: "ability-activated", abilityId: definition.id, handle });
    const context = {
      system: this,
      handle,
      target: options.target,
      payload: options.payload,
      applyEffect: (effect, target = options.target ?? this, parameters) => target.applyEffect(effect, { source: this, parameters }),
      end: () => this.endAbility(handle)
    };
    try {
      for (const application of definition.effects ?? []) {
        const target = application.target === "owner" ? this : options.target;
        if (!target) continue;
        const result = target.applyEffect(application.effect, {
          source: this,
          parameters: application.parameters
        });
        if (!result.ok) {
          this.endAbility(handle, true);
          return { ok: false, reason: "effect-rejected" };
        }
      }
      definition.onActivate?.(context);
    } catch (error) {
      this.endAbility(handle, true);
      throw error;
    }
    if ((definition.lifecycle ?? "instant") === "instant") this.endAbility(handle);
    return { ok: true, handle };
  }
  endAbility(handle, cancelled = false) {
    const active = this.activeAbilities.get(handle);
    if (!active) return false;
    this.activeAbilities.delete(handle);
    this.removeGrantedTags(active.granted.definition.ownedTags);
    active.granted.definition.onEnd?.({
      system: this,
      handle,
      target: active.target,
      payload: active.payload,
      cancelled
    });
    this.emit({
      type: "ability-ended",
      abilityId: active.granted.definition.id,
      handle,
      cancelled
    });
    return true;
  }
  canApplyEffect(definition) {
    this.validateEffectDefinition(definition);
    return this.matchesRequirements(definition.requirements);
  }
  applyEffect(definition, options = {}) {
    this.validateEffectDefinition(definition);
    if (!this.matchesRequirements(definition.requirements)) {
      return { ok: false, reason: "tag-requirements" };
    }
    const parameters = freezeParameters(options.parameters);
    const context = { source: options.source, target: this, parameters };
    if (definition.lifetime.kind === "instant") {
      const modifiers = this.resolveModifiers(definition.modifiers, context, this.nextEffectOrder++);
      this.applyBaseModifiers(modifiers);
      this.emit({ type: "effect-applied", effectId: definition.id });
      return { ok: true };
    }
    const stackTarget = this.findStackTarget(definition, options.source);
    if (stackTarget) {
      const stacking = definition.stacking;
      if (!stacking) throw new Error("\u5185\u90E8\u9519\u8BEF\uFF1A\u7F3A\u5C11 Effect stacking \u5B9A\u4E49");
      if (stackTarget.resolvedStacks.length < stacking.maxStacks) {
        const order2 = stackTarget.order + stackTarget.resolvedStacks.length / 1e3;
        const resolved2 = this.resolveModifiers(definition.modifiers, context, order2);
        stackTarget.resolvedStacks.push(resolved2);
        if (definition.period?.executeOnApply) this.applyBaseModifiers(resolved2);
        this.emit({
          type: "effect-stacked",
          effectId: definition.id,
          handle: stackTarget.handle,
          stacks: stackTarget.resolvedStacks.length
        });
      }
      if (stacking.refreshDurationOnApply && definition.lifetime.kind === "timed") {
        stackTarget.remainingSeconds = definition.lifetime.seconds;
      }
      this.recalculateAttributes();
      return { ok: true, handle: stackTarget.handle };
    }
    const handle = `effect:${this.nextEffectHandle++}`;
    const order = this.nextEffectOrder++;
    const resolved = this.resolveModifiers(definition.modifiers, context, order);
    const active = {
      handle,
      definition,
      source: options.source,
      parameters,
      order,
      stackKey: definition.stacking?.key ?? (definition.stacking ? definition.id : void 0),
      resolvedStacks: [resolved],
      remainingSeconds: definition.lifetime.kind === "timed" ? definition.lifetime.seconds : void 0,
      periodRemainingSeconds: definition.period?.seconds
    };
    this.activeEffects.set(handle, active);
    this.addGrantedTags(definition.grantedTags);
    if (definition.period?.executeOnApply) this.applyBaseModifiers(resolved);
    this.recalculateAttributes();
    this.emit({ type: "effect-applied", effectId: definition.id, handle });
    return { ok: true, handle };
  }
  removeEffect(handle) {
    return this.removeEffectInternal(handle, "removed");
  }
  removeEffectsByTag(tag) {
    const handles = [...this.activeEffects.values()].filter((effect) => (effect.definition.grantedTags ?? []).some((owned) => tagMatches(owned, tag))).map((effect) => effect.handle);
    for (const handle of handles) this.removeEffectInternal(handle, "removed");
    return handles.length;
  }
  getCooldownRemaining(groupOrAbilityId) {
    return this.cooldowns.get(groupOrAbilityId) ?? 0;
  }
  update(deltaSeconds) {
    if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) {
      throw new RangeError("AbilitySystem.update deltaSeconds \u5FC5\u987B\u662F\u975E\u8D1F\u6709\u9650\u6570\u5B57");
    }
    if (deltaSeconds === 0) return;
    this.elapsedSeconds += deltaSeconds;
    for (const [group, remaining] of this.cooldowns) {
      const next = Math.max(remaining - deltaSeconds, 0);
      if (next <= TIME_EPSILON) this.cooldowns.delete(group);
      else this.cooldowns.set(group, next);
    }
    for (const effect of [...this.activeEffects.values()]) {
      const availableTime = effect.remainingSeconds === void 0 ? deltaSeconds : Math.min(deltaSeconds, effect.remainingSeconds);
      if (effect.periodRemainingSeconds !== void 0) {
        effect.periodRemainingSeconds -= availableTime;
        while (effect.periodRemainingSeconds <= TIME_EPSILON) {
          for (const stack of effect.resolvedStacks) this.applyBaseModifiers(stack);
          effect.periodRemainingSeconds += effect.definition.period?.seconds ?? Number.POSITIVE_INFINITY;
        }
      }
      if (effect.remainingSeconds !== void 0) {
        effect.remainingSeconds -= deltaSeconds;
        if (effect.remainingSeconds <= TIME_EPSILON) {
          this.removeEffectInternal(effect.handle, "expired");
        }
      }
    }
  }
  createSnapshot() {
    const grantedTags = [...this.grantedTagCounts].filter(([, count]) => count > 0).map(([tag]) => tag);
    const abilities = [...this.abilities.values()].map((granted) => ({
      handle: granted.handle,
      abilityId: granted.definition.id,
      active: this.activeAbilities.has(granted.handle),
      sourceId: granted.sourceId
    }));
    const effects = [...this.activeEffects.values()].map((effect) => ({
      handle: effect.handle,
      effectId: effect.definition.id,
      sourceId: effect.source?.ownerId,
      remainingSeconds: effect.remainingSeconds,
      periodRemainingSeconds: effect.periodRemainingSeconds,
      stacks: effect.resolvedStacks.length,
      parameters: effect.parameters
    }));
    return {
      ownerId: this.ownerId,
      elapsedSeconds: this.elapsedSeconds,
      attributes: this.attributes.createSnapshot(),
      looseTags: this.looseTags.toArray(),
      grantedTags,
      abilities,
      effects,
      cooldowns: Object.fromEntries(this.cooldowns)
    };
  }
  matchesRequirements(requirements, additionalTags = []) {
    if (!requirements) return true;
    const hasTag = (query) => this.hasTag(query) || additionalTags.some((tag) => tagMatches(tag, query));
    if (requirements.all && !requirements.all.every(hasTag)) return false;
    if (requirements.any?.length && !requirements.any.some(hasTag)) return false;
    if (requirements.none && requirements.none.some(hasTag)) return false;
    return true;
  }
  isBlockedByActiveAbility(candidate) {
    const candidateTags = new TagContainer(candidate.tags ?? []);
    for (const active of this.activeAbilities.values()) {
      const blockedTags = active.granted.definition.blockAbilitiesWithTags ?? [];
      if (candidateTags.hasAny(blockedTags)) return true;
    }
    return false;
  }
  isConcurrencyBlocked(candidate) {
    if ((candidate.concurrency ?? "parallel") === "parallel") return false;
    const group = candidate.concurrencyGroup ?? "default";
    return [...this.activeAbilities.values()].some((active) => (active.granted.definition.concurrencyGroup ?? "default") === group && (active.granted.definition.concurrency ?? "parallel") === "blocking");
  }
  cancelAbilitiesFor(candidate) {
    const queries = candidate.cancelAbilitiesWithTags ?? [];
    if (queries.length === 0) return;
    for (const active of [...this.activeAbilities.values()]) {
      const activeTags = new TagContainer(active.granted.definition.tags ?? []);
      if (activeTags.hasAny(queries)) this.endAbility(active.granted.handle, true);
    }
  }
  cancelReplaceableAbilitiesFor(candidate) {
    if ((candidate.concurrency ?? "parallel") !== "blocking") return;
    const group = candidate.concurrencyGroup ?? "default";
    for (const active of [...this.activeAbilities.values()]) {
      if ((active.granted.definition.concurrencyGroup ?? "default") !== group) continue;
      if ((active.granted.definition.concurrency ?? "parallel") === "replaceable") {
        this.endAbility(active.granted.handle, true);
      }
    }
  }
  findStackTarget(definition, source) {
    if (!definition.stacking) return void 0;
    const key = definition.stacking.key ?? definition.id;
    return [...this.activeEffects.values()].find((effect) => effect.stackKey === key && (definition.stacking?.scope !== "source" || effect.source?.ownerId === source?.ownerId));
  }
  resolveModifiers(modifiers, context, order) {
    return (modifiers ?? []).map((modifier, index) => {
      const magnitude = typeof modifier.magnitude === "function" ? modifier.magnitude(context) : modifier.magnitude;
      if (!Number.isFinite(magnitude)) {
        throw new TypeError(`Effect ${context.target.ownerId} \u7684 Modifier magnitude \u5FC5\u987B\u662F\u6709\u9650\u6570\u5B57`);
      }
      if (!this.attributes.has(modifier.attributeId)) {
        throw new Error(`Effect \u5F15\u7528\u4E86\u672A\u77E5\u5C5E\u6027\uFF1A${modifier.attributeId}`);
      }
      return {
        attributeId: modifier.attributeId,
        operation: modifier.operation,
        magnitude,
        priority: modifier.priority ?? 0,
        order: order * 1e3 + index
      };
    });
  }
  applyBaseModifiers(modifiers) {
    if (modifiers.length === 0) return;
    for (const modifier of modifiers) {
      this.attributes.modifyBaseValue(
        modifier.attributeId,
        modifier.operation,
        modifier.magnitude
      );
    }
    this.recalculateAttributes();
  }
  recalculateAttributes() {
    const persistentModifiers = [];
    for (const effect of this.activeEffects.values()) {
      if (effect.definition.period) continue;
      for (const stack of effect.resolvedStacks) persistentModifiers.push(...stack);
    }
    this.attributes.recalculate(persistentModifiers);
  }
  removeEffectInternal(handle, reason) {
    const effect = this.activeEffects.get(handle);
    if (!effect) return false;
    this.activeEffects.delete(handle);
    this.removeGrantedTags(effect.definition.grantedTags);
    this.recalculateAttributes();
    this.emit({ type: "effect-removed", effectId: effect.definition.id, handle, reason });
    return true;
  }
  addGrantedTags(tags) {
    for (const tagLike of tags ?? []) {
      const tag = defineTag(tagLike);
      this.grantedTagCounts.set(tag, (this.grantedTagCounts.get(tag) ?? 0) + 1);
    }
  }
  removeGrantedTags(tags) {
    for (const tagLike of tags ?? []) {
      const tag = defineTag(tagLike);
      const next = (this.grantedTagCounts.get(tag) ?? 0) - 1;
      if (next > 0) this.grantedTagCounts.set(tag, next);
      else this.grantedTagCounts.delete(tag);
    }
  }
  validateAbilityDefinition(definition) {
    assertDefinitionId(definition.id, "Ability");
    for (const cost of definition.costs ?? []) {
      assertPositiveFinite(cost.amount, `Ability ${definition.id} \u7684 cost amount`);
      if (!this.attributes.has(cost.attributeId)) {
        throw new Error(`Ability ${definition.id} \u5F15\u7528\u4E86\u672A\u77E5\u6D88\u8017\u5C5E\u6027\uFF1A${cost.attributeId}`);
      }
    }
    if (definition.cooldown) {
      assertPositiveFinite(definition.cooldown.seconds, `Ability ${definition.id} \u7684 cooldown`);
    }
    for (const tag of [
      ...definition.tags ?? [],
      ...definition.ownedTags ?? [],
      ...definition.cancelAbilitiesWithTags ?? [],
      ...definition.blockAbilitiesWithTags ?? []
    ]) defineTag(tag);
  }
  validateEffectDefinition(definition) {
    assertDefinitionId(definition.id, "Effect");
    if (definition.lifetime.kind === "timed") {
      assertPositiveFinite(definition.lifetime.seconds, `Effect ${definition.id} \u7684 duration`);
    }
    if (definition.period) {
      if (definition.lifetime.kind === "instant") {
        throw new Error(`Instant Effect ${definition.id} \u4E0D\u80FD\u8BBE\u7F6E period`);
      }
      assertPositiveFinite(definition.period.seconds, `Effect ${definition.id} \u7684 period`);
    }
    if (definition.stacking) {
      if (definition.lifetime.kind === "instant") {
        throw new Error(`Instant Effect ${definition.id} \u4E0D\u80FD\u8BBE\u7F6E stacking`);
      }
      if (!Number.isInteger(definition.stacking.maxStacks) || definition.stacking.maxStacks < 1) {
        throw new RangeError(`Effect ${definition.id} \u7684 maxStacks \u5FC5\u987B\u662F\u6B63\u6574\u6570`);
      }
    }
    for (const modifier of definition.modifiers ?? []) {
      if (!this.attributes.has(modifier.attributeId)) {
        throw new Error(`Effect ${definition.id} \u5F15\u7528\u4E86\u672A\u77E5\u5C5E\u6027\uFF1A${modifier.attributeId}`);
      }
    }
    for (const tag of definition.grantedTags ?? []) defineTag(tag);
  }
  emit(event) {
    for (const listener of this.listeners) listener(event);
  }
};
export {
  AbilitySystem,
  AttributeSet,
  JavascriptAttributeBackend,
  defineTag,
  isValidTag,
  tagMatches
};
