import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 810 } });
const errs = [];
page.on('pageerror', e => errs.push(String(e)));
await page.goto('http://localhost:8123/?oyaw=0.8', { waitUntil: 'networkidle' });
await page.waitForTimeout(3500);
await page.keyboard.down('Shift');
await page.keyboard.down('w');
await page.waitForTimeout(3000);
await page.screenshot({ path: 'c2_wake.png' });
await page.keyboard.up('w');
await page.keyboard.up('Shift');
console.log(errs.length ? 'ERRORS: '+errs.join('; ') : 'no errors');
await browser.close();
