import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 810 } });
const errs = [];
page.on('pageerror', e => errs.push(String(e)));
await page.goto('http://localhost:8123/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3500);
const before = await page.evaluate(() => window.__dbg.sub.position.toArray());
await page.keyboard.down('w');
await page.waitForTimeout(2500);
await page.keyboard.down('a');
await page.waitForTimeout(1800);
await page.keyboard.up('a');
await page.waitForTimeout(800);
await page.screenshot({ path: 'r2_drive.png' });
await page.keyboard.up('w');
const after = await page.evaluate(() => window.__dbg.sub.position.toArray());
const d = Math.hypot(after[0]-before[0], after[2]-before[2]);
console.log('sub moved', d.toFixed(1), 'units;', errs.length ? 'ERRORS: '+errs.join('; ') : 'no errors');
await browser.close();
